name: Publish "flwr_attacks" to PyPI

on:
    push:
      branches:
        - main 
  

jobs:
    build-and-publish:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
          with:
            fetch-depth: 0
    
        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.8'
    
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install poetry
            poetry config virtualenvs.create false
    
        - name: Build and publish to PyPI
          env:
            POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_API_TOKEN }}
          run: |
            poetry build
            poetry publish --username __token__ --password ${{ secrets.PYPI_API_TOKEN }}